# Generated by Django 3.0.2 on 2020-01-28 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('desc', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 1, 28, 8, 6, 30, 511271, tzinfo=utc))),
                ('end_date', models.DateTimeField()),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Ranks')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Statuses')),
            ],
        ),
    ]
