# Generated by Django 3.0.2 on 2020-01-28 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 8, 23, 25, 913178, tzinfo=utc)),
        ),
    ]
