# Generated by Django 3.0.2 on 2020-01-28 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200128_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 8, 29, 41, 711166, tzinfo=utc)),
        ),
    ]
