# Generated by Django 3.0.2 on 2020-01-28 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200128_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 8, 37, 49, 760980, tzinfo=utc)),
        ),
    ]
