# Generated by Django 3.0.2 on 2020-01-28 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200128_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 8, 42, 3, 394611, tzinfo=utc)),
        ),
    ]
