# Generated by Django 3.0.2 on 2020-02-16 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    atomic = False
    

    dependencies = [
        ('stock', '0005_auto_20200128_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('desc', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 2, 16, 16, 29, 36, 522187, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ranks',
            new_name='Rank',
        ),
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Rank'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Status'),
        ),
    ]
